import 'package:flutter/material.dart';

class IconosScreen extends StatefulWidget {
  const IconosScreen({super.key});

  @override
  State<IconosScreen> createState() => _IconosScreenState();
}

class _IconosScreenState extends State<IconosScreen> {
  final _controller = TextEditingController();
  String _busqueda = '';

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final filtrados = _iconosFlutter.entries
        .where((e) => e.key.contains(_busqueda.toLowerCase()))
        .toList();

    return Scaffold(
      appBar: AppBar(title: const Text('Iconos Flutter')),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(12, 12, 12, 4),
            child: TextField(
              controller: _controller,
              decoration: InputDecoration(
                hintText: 'Buscar icono...',
                prefixIcon: const Icon(Icons.search),
                suffixIcon: _busqueda.isNotEmpty
                    ? IconButton(
                        icon: const Icon(Icons.close),
                        onPressed: () {
                          _controller.clear();
                          setState(() => _busqueda = '');
                        },
                      )
                    : null,
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                contentPadding: const EdgeInsets.symmetric(vertical: 10),
              ),
              onChanged: (v) => setState(() => _busqueda = v.trim()),
            ),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
            child: Align(
              alignment: Alignment.centerLeft,
              child: Text(
                '${filtrados.length} iconos',
                style: Theme.of(context).textTheme.bodySmall,
              ),
            ),
          ),
          Expanded(
            child: GridView.builder(
              padding: const EdgeInsets.all(10),
              gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 4,
                childAspectRatio: 0.85,
                crossAxisSpacing: 8,
                mainAxisSpacing: 8,
              ),
              itemCount: filtrados.length,
              itemBuilder: (context, i) {
                final entry = filtrados[i];
                return Card(
                  child: InkWell(
                    borderRadius: BorderRadius.circular(12),
                    onTap: () => ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(
                        content: Text('Icons.${entry.key}'),
                        duration: const Duration(seconds: 2),
                      ),
                    ),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(entry.value, size: 28),
                        const SizedBox(height: 6),
                        Padding(
                          padding: const EdgeInsets.symmetric(horizontal: 4),
                          child: Text(
                            entry.key,
                            style: Theme.of(context).textTheme.labelSmall?.copyWith(fontSize: 9),
                            textAlign: TextAlign.center,
                            maxLines: 2,
                            overflow: TextOverflow.ellipsis,
                          ),
                        ),
                      ],
                    ),
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}

const _iconosFlutter = <String, IconData>{
  // Acciones
  'add': Icons.add,
  'add_circle': Icons.add_circle,
  'add_circle_outline': Icons.add_circle_outline,
  'remove': Icons.remove,
  'remove_circle': Icons.remove_circle,
  'delete': Icons.delete,
  'delete_outline': Icons.delete_outline,
  'edit': Icons.edit,
  'save': Icons.save,
  'copy': Icons.copy,
  'cut': Icons.cut,
  'paste': Icons.paste,
  'undo': Icons.undo,
  'redo': Icons.redo,
  'search': Icons.search,
  'close': Icons.close,
  'check': Icons.check,
  'check_circle': Icons.check_circle,
  'check_circle_outline': Icons.check_circle_outline,
  'cancel': Icons.cancel,
  'block': Icons.block,
  'share': Icons.share,
  'download': Icons.download,
  'upload': Icons.upload,
  'refresh': Icons.refresh,
  'sync': Icons.sync,
  'filter_list': Icons.filter_list,
  'sort': Icons.sort,
  'swap_vert': Icons.swap_vert,
  'swap_horiz': Icons.swap_horiz,
  'open_in_new': Icons.open_in_new,
  'launch': Icons.launch,
  'link': Icons.link,
  'attachment': Icons.attachment,
  'push_pin': Icons.push_pin,
  'bookmark': Icons.bookmark,
  'bookmark_outline': Icons.bookmark_outline,
  'favorite': Icons.favorite,
  'favorite_outline': Icons.favorite_outline,
  'star': Icons.star,
  'star_outline': Icons.star_outline,
  'star_half': Icons.star_half,
  'thumb_up': Icons.thumb_up,
  'thumb_down': Icons.thumb_down,
  'flag': Icons.flag,
  'report': Icons.report,
  'info': Icons.info,
  'info_outline': Icons.info_outline,
  'help': Icons.help,
  'help_outline': Icons.help_outline,
  'warning': Icons.warning,
  'warning_amber': Icons.warning_amber,
  'error': Icons.error,
  'error_outline': Icons.error_outline,
  'done': Icons.done,
  'done_all': Icons.done_all,
  'zoom_in': Icons.zoom_in,
  'zoom_out': Icons.zoom_out,
  'lock': Icons.lock,
  'lock_open': Icons.lock_open,
  'visibility': Icons.visibility,
  'visibility_off': Icons.visibility_off,
  'fullscreen': Icons.fullscreen,
  'fullscreen_exit': Icons.fullscreen_exit,

  // Navegación
  'arrow_back': Icons.arrow_back,
  'arrow_forward': Icons.arrow_forward,
  'arrow_upward': Icons.arrow_upward,
  'arrow_downward': Icons.arrow_downward,
  'arrow_back_ios': Icons.arrow_back_ios,
  'arrow_forward_ios': Icons.arrow_forward_ios,
  'chevron_left': Icons.chevron_left,
  'chevron_right': Icons.chevron_right,
  'expand_more': Icons.expand_more,
  'expand_less': Icons.expand_less,
  'unfold_more': Icons.unfold_more,
  'unfold_less': Icons.unfold_less,
  'menu': Icons.menu,
  'menu_open': Icons.menu_open,
  'more_vert': Icons.more_vert,
  'more_horiz': Icons.more_horiz,
  'home': Icons.home,
  'home_outlined': Icons.home_outlined,
  'dashboard': Icons.dashboard,
  'apps': Icons.apps,
  'grid_view': Icons.grid_view,
  'list': Icons.list,
  'view_list': Icons.view_list,
  'view_module': Icons.view_module,
  'tune': Icons.tune,
  'settings': Icons.settings,
  'manage_accounts': Icons.manage_accounts,
  'logout': Icons.logout,
  'login': Icons.login,

  // Comunicación
  'phone': Icons.phone,
  'call': Icons.call,
  'call_end': Icons.call_end,
  'call_missed': Icons.call_missed,
  'voicemail': Icons.voicemail,
  'email': Icons.email,
  'mail': Icons.mail,
  'mail_outline': Icons.mail_outline,
  'chat': Icons.chat,
  'chat_bubble': Icons.chat_bubble,
  'message': Icons.message,
  'sms': Icons.sms,
  'send': Icons.send,
  'forum': Icons.forum,
  'comment': Icons.comment,
  'notifications': Icons.notifications,
  'notifications_none': Icons.notifications_none,
  'notifications_off': Icons.notifications_off,
  'notifications_active': Icons.notifications_active,
  'wifi': Icons.wifi,
  'wifi_off': Icons.wifi_off,
  'bluetooth': Icons.bluetooth,
  'bluetooth_disabled': Icons.bluetooth_disabled,
  'signal_cellular_4_bar': Icons.signal_cellular_4_bar,
  'language': Icons.language,
  'translate': Icons.translate,
  'rss_feed': Icons.rss_feed,

  // Personas
  'person': Icons.person,
  'person_outline': Icons.person_outline,
  'person_add': Icons.person_add,
  'person_remove': Icons.person_remove,
  'group': Icons.group,
  'group_add': Icons.group_add,
  'people': Icons.people,
  'account_circle': Icons.account_circle,
  'account_box': Icons.account_box,
  'badge': Icons.badge,
  'face': Icons.face,
  'contacts': Icons.contacts,
  'contact_page': Icons.contact_page,
  'supervisor_account': Icons.supervisor_account,
  'engineering': Icons.engineering,

  // Media
  'play_arrow': Icons.play_arrow,
  'play_circle': Icons.play_circle,
  'pause': Icons.pause,
  'pause_circle': Icons.pause_circle,
  'stop': Icons.stop,
  'stop_circle': Icons.stop_circle,
  'skip_next': Icons.skip_next,
  'skip_previous': Icons.skip_previous,
  'fast_forward': Icons.fast_forward,
  'fast_rewind': Icons.fast_rewind,
  'replay': Icons.replay,
  'replay_10': Icons.replay_10,
  'forward_10': Icons.forward_10,
  'volume_up': Icons.volume_up,
  'volume_down': Icons.volume_down,
  'volume_off': Icons.volume_off,
  'volume_mute': Icons.volume_mute,
  'mic': Icons.mic,
  'mic_off': Icons.mic_off,
  'videocam': Icons.videocam,
  'videocam_off': Icons.videocam_off,
  'music_note': Icons.music_note,
  'headphones': Icons.headphones,
  'headset': Icons.headset,
  'queue_music': Icons.queue_music,
  'shuffle': Icons.shuffle,
  'repeat': Icons.repeat,
  'repeat_one': Icons.repeat_one,
  'library_music': Icons.library_music,
  'album': Icons.album,
  'audiotrack': Icons.audiotrack,
  'radio': Icons.radio,
  'live_tv': Icons.live_tv,
  'movie': Icons.movie,
  'slideshow': Icons.slideshow,
  'subscriptions': Icons.subscriptions,

  // Imágenes y archivos
  'image': Icons.image,
  'image_not_supported': Icons.image_not_supported,
  'photo': Icons.photo,
  'photo_camera': Icons.photo_camera,
  'camera_alt': Icons.camera_alt,
  'camera': Icons.camera,
  'camera_front': Icons.camera_front,
  'camera_rear': Icons.camera_rear,
  'collections': Icons.collections,
  'photo_library': Icons.photo_library,
  'panorama': Icons.panorama,
  'crop': Icons.crop,
  'rotate_left': Icons.rotate_left,
  'rotate_right': Icons.rotate_right,
  'flip': Icons.flip,
  'folder': Icons.folder,
  'folder_open': Icons.folder_open,
  'folder_shared': Icons.folder_shared,
  'create_new_folder': Icons.create_new_folder,
  'description': Icons.description,
  'article': Icons.article,
  'insert_drive_file': Icons.insert_drive_file,
  'picture_as_pdf': Icons.picture_as_pdf,
  'cloud': Icons.cloud,
  'cloud_upload': Icons.cloud_upload,
  'cloud_download': Icons.cloud_download,
  'cloud_done': Icons.cloud_done,
  'cloud_off': Icons.cloud_off,
  'backup': Icons.backup,
  'archive': Icons.archive,
  'unarchive': Icons.unarchive,

  // Mapas y lugares
  'map': Icons.map,
  'location_on': Icons.location_on,
  'location_off': Icons.location_off,
  'my_location': Icons.my_location,
  'place': Icons.place,
  'near_me': Icons.near_me,
  'directions': Icons.directions,
  'directions_walk': Icons.directions_walk,
  'navigation': Icons.navigation,
  'explore': Icons.explore,
  'terrain': Icons.terrain,
  'traffic': Icons.traffic,
  'pin_drop': Icons.pin_drop,
  'add_location': Icons.add_location,
  'layers': Icons.layers,
  'streetview': Icons.streetview,

  // Tiempo y calendario
  'calendar_today': Icons.calendar_today,
  'calendar_month': Icons.calendar_month,
  'event': Icons.event,
  'event_available': Icons.event_available,
  'event_busy': Icons.event_busy,
  'schedule': Icons.schedule,
  'access_time': Icons.access_time,
  'alarm': Icons.alarm,
  'alarm_on': Icons.alarm_on,
  'alarm_off': Icons.alarm_off,
  'timer': Icons.timer,
  'timer_off': Icons.timer_off,
  'hourglass_empty': Icons.hourglass_empty,
  'hourglass_top': Icons.hourglass_top,
  'hourglass_bottom': Icons.hourglass_bottom,
  'date_range': Icons.date_range,
  'today': Icons.today,
  'update': Icons.update,
  'history': Icons.history,

  // Dispositivos y hardware
  'phone_android': Icons.phone_android,
  'phone_iphone': Icons.phone_iphone,
  'tablet': Icons.tablet,
  'laptop': Icons.laptop,
  'desktop_windows': Icons.desktop_windows,
  'tv': Icons.tv,
  'watch': Icons.watch,
  'keyboard': Icons.keyboard,
  'mouse': Icons.mouse,
  'speaker': Icons.speaker,
  'battery_full': Icons.battery_full,
  'battery_alert': Icons.battery_alert,
  'battery_charging_full': Icons.battery_charging_full,
  'flash_on': Icons.flash_on,
  'flash_off': Icons.flash_off,
  'brightness_high': Icons.brightness_high,
  'brightness_low': Icons.brightness_low,
  'memory': Icons.memory,
  'storage': Icons.storage,
  'usb': Icons.usb,
  'sd_card': Icons.sd_card,
  'sim_card': Icons.sim_card,
  'router': Icons.router,
  'print': Icons.print,

  // Compras y finanzas
  'shopping_cart': Icons.shopping_cart,
  'shopping_bag': Icons.shopping_bag,
  'store': Icons.store,
  'storefront': Icons.storefront,
  'payment': Icons.payment,
  'credit_card': Icons.credit_card,
  'attach_money': Icons.attach_money,
  'money': Icons.money,
  'savings': Icons.savings,
  'account_balance': Icons.account_balance,
  'account_balance_wallet': Icons.account_balance_wallet,
  'local_offer': Icons.local_offer,
  'redeem': Icons.redeem,
  'receipt': Icons.receipt,
  'receipt_long': Icons.receipt_long,
  'sell': Icons.sell,

  // Transporte
  'directions_car': Icons.directions_car,
  'directions_bus': Icons.directions_bus,
  'directions_bike': Icons.directions_bike,
  'directions_boat': Icons.directions_boat,
  'directions_run': Icons.directions_run,
  'flight': Icons.flight,
  'flight_takeoff': Icons.flight_takeoff,
  'flight_land': Icons.flight_land,
  'train': Icons.train,
  'subway': Icons.subway,
  'local_taxi': Icons.local_taxi,
  'local_shipping': Icons.local_shipping,
  'electric_car': Icons.electric_car,
  'electric_bike': Icons.electric_bike,
  'two_wheeler': Icons.two_wheeler,

  // Alimentación y lugares
  'restaurant': Icons.restaurant,
  'restaurant_menu': Icons.restaurant_menu,
  'local_cafe': Icons.local_cafe,
  'local_bar': Icons.local_bar,
  'local_pizza': Icons.local_pizza,
  'fastfood': Icons.fastfood,
  'dinner_dining': Icons.dinner_dining,
  'hotel': Icons.hotel,
  'local_hospital': Icons.local_hospital,
  'local_pharmacy': Icons.local_pharmacy,
  'local_gas_station': Icons.local_gas_station,
  'local_parking': Icons.local_parking,
  'school': Icons.school,
  'business': Icons.business,
  'business_center': Icons.business_center,
  'park': Icons.park,
  'museum': Icons.museum,
  'stadium': Icons.stadium,

  // Datos y tecnología
  'code': Icons.code,
  'data_object': Icons.data_object,
  'data_array': Icons.data_array,
  'terminal': Icons.terminal,
  'api': Icons.api,
  'developer_mode': Icons.developer_mode,
  'developer_board': Icons.developer_board,
  'bug_report': Icons.bug_report,
  'build': Icons.build,
  'build_circle': Icons.build_circle,
  'handyman': Icons.handyman,
  'construction': Icons.construction,
  'integration_instructions': Icons.integration_instructions,
  'analytics': Icons.analytics,
  'bar_chart': Icons.bar_chart,
  'pie_chart': Icons.pie_chart,
  'show_chart': Icons.show_chart,
  'trending_up': Icons.trending_up,
  'trending_down': Icons.trending_down,
  'trending_flat': Icons.trending_flat,
  'table_chart': Icons.table_chart,
  'functions': Icons.functions,
  'calculate': Icons.calculate,

  // UI y formato
  'light_mode': Icons.light_mode,
  'dark_mode': Icons.dark_mode,
  'palette': Icons.palette,
  'color_lens': Icons.color_lens,
  'format_paint': Icons.format_paint,
  'brush': Icons.brush,
  'format_bold': Icons.format_bold,
  'format_italic': Icons.format_italic,
  'format_underlined': Icons.format_underlined,
  'format_size': Icons.format_size,
  'format_list_bulleted': Icons.format_list_bulleted,
  'format_list_numbered': Icons.format_list_numbered,
  'format_align_left': Icons.format_align_left,
  'format_align_center': Icons.format_align_center,
  'format_align_right': Icons.format_align_right,
  'text_fields': Icons.text_fields,
  'title': Icons.title,
  'subject': Icons.subject,
  'wrap_text': Icons.wrap_text,

  // Seguridad
  'security': Icons.security,
  'shield': Icons.shield,
  'verified_user': Icons.verified_user,
  'verified': Icons.verified,
  'fingerprint': Icons.fingerprint,
  'password': Icons.password,
  'key': Icons.key,
  'vpn_key': Icons.vpn_key,
  'https': Icons.https,
  'policy': Icons.policy,
  'privacy_tip': Icons.privacy_tip,

  // Miscelánea
  'qr_code': Icons.qr_code,
  'qr_code_scanner': Icons.qr_code_scanner,
  'science': Icons.science,
  'eco': Icons.eco,
  'recycling': Icons.recycling,
  'ac_unit': Icons.ac_unit,
  'wb_sunny': Icons.wb_sunny,
  'nights_stay': Icons.nights_stay,
  'sports': Icons.sports,
  'fitness_center': Icons.fitness_center,
  'sports_soccer': Icons.sports_soccer,
  'sports_basketball': Icons.sports_basketball,
  'sports_esports': Icons.sports_esports,
  'toys': Icons.toys,
  'child_care': Icons.child_care,
  'accessible': Icons.accessible,
  'accessibility_new': Icons.accessibility_new,
  'self_improvement': Icons.self_improvement,
  'medical_services': Icons.medical_services,
  'health_and_safety': Icons.health_and_safety,
  'psychology': Icons.psychology,
  'sentiment_satisfied': Icons.sentiment_satisfied,
  'sentiment_dissatisfied': Icons.sentiment_dissatisfied,
  'sentiment_neutral': Icons.sentiment_neutral,
  'mood': Icons.mood,
  'mood_bad': Icons.mood_bad,
  'celebration': Icons.celebration,
  'cake': Icons.cake,
  'auto_awesome': Icons.auto_awesome,
  'bolt': Icons.bolt,
  'whatshot': Icons.whatshot,
  'new_releases': Icons.new_releases,
  'grade': Icons.grade,
  'workspace_premium': Icons.workspace_premium,
  'military_tech': Icons.military_tech,
  'emoji_events': Icons.emoji_events,
  'emoji_objects': Icons.emoji_objects,
  'lightbulb': Icons.lightbulb,
  'lightbulb_outline': Icons.lightbulb_outline,
  'catching_pokemon': Icons.catching_pokemon,
  'monitor': Icons.monitor,
  'music_note_outlined': Icons.music_note_outlined,
};
